hydra:
  launcher:
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    timeout_min: 120  # 2 hours
    cpus_per_task: 1
    tasks_per_node: 1
    mem_per_cpu: 5G  
    nodes: 1
    name: "U_test"
    array_parallelism: 270  # Number of jobs to run in parallel
    additional_parameters:
      account: "ls_krausea"  
      gpus: "rtx_3090:1" # NVIDIA GeForce RTX 3090 with 24GiB
    comment: "test comment"
    setup: 
      - "module load gcc/8.2.0 python_gpu/3.11.2"
      - "module load eth_proxy"
      - "source ~/.venv/work_jax6/bin/activate"
      - "export WANDB__SERVICE_WAIT=300"


